#!/usr/bin/env bash
#
# compile
# https://github.com/jubinmathew1995/compile
#
# Generates output of the executed program file.
#
# Examples:
#
#   $ compile file_name.cpp
#   $ compile file_name.c

  help()
  {
    cat <<EOF

    USAGE:
      $ compile [-h|--help] FILENAME,...

    EXAMPLES:
      $ compile file_name.cpp

      $ compile file_name.c
EOF
  }

  # show help for no arguments if stdin is a terminal
  if [ $# -eq 0 ] || [ "$1" == '-h' ] || [ "$1" == '--help' ]
  then
    help
    exit 0
  fi

if [ $# -eq 1 ] # when only single file is send for execution.
then
  if [[ ${1: -4} == ".cpp" ]] # checking extension for execution
  then
    g++ --std=c++14 $1 -o $PWD/a.out   # generating the object file in the current working directory.
  elif [[ ${1: -2} == ".c" ]] # checking extension for execution
  then
    gcc --std=c11 $1 -o $PWD/a.out   # generating the object file in the current working directory.
  else
    echo "Unrecognised file extension."
    exit
  fi

  if [ $? -eq 0 ] # if any error NOT occured then execute the object file.
  then
    echo "====> Compiled Successfully"
    echo "====> Executing"
    $PWD/a.out # execute the object file.
    # rm $PWD/a.out  # remove the executed object file.
    echo "====> Execution Complete"
  else
    echo "====> Compile Failed"
  fi
fi
